#fichier playbook ansible installation observium sur centos 9
#installation de ces paquets via ansible "wget httpd php php-opcache php-mysqlnd php-gd php-posix php-pear cronie net-snmp net-snmp-utils fping mariadb-server mariadb rrdtool subversion whois ipmitool graphviz ImageMagick php-sodium python3 python3-PyMySQL"

- hosts: all
  become: yes
  become_method: sudo
  become_user: root
  vars:
    observium_user: etudiant
    observium_password: Etudiant_007
    observium_level: 10
  tasks:
    - name: install dnf-utils
      yum:
        name: dnf-utils
        state: present
    - name: install epel-release-latest-9
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
        state: present
    - name: install epel-next-release-latest-9
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-next-release-latest-9.noarch.rpm
        state: present
    - name: install remi-release-9
      yum:
        name: http://rpms.remirepo.net/enterprise/remi-release-9.rpm
        state: present
    - name: install php:remi-8.2
      yum:
        name: php:remi-8.2
        state: present
    - name: install php
      yum:
        name: php
        state: present
    - name: install php-opcache
      yum:
        name: php-opcache
        state: present
    - name: install php-mysqlnd
      yum:
        name: php-mysqlnd
        state: present
    - name: install php-gd
      yum:
        name: php-gd
        state: present
    - name: install php-posix
      yum:
        name: php-posix
        state: present
    - name: install php-pear  
      yum:
        name: php-pear
        state: present
    - name: install cronie  
      yum:
        name: cronie
        state: present
    - name: install net-snmp
      yum:
        name: net-snmp
        state: present
    - name: install net-snmp-utils
      yum:
        name: net-snmp-utils
        state: present
    - name: install fping
      yum:
        name: fping
        state: present
    - name: install mariadb-server
      yum:
        name: mariadb-server
        state: present
    - name: install mariadb
      yum:
        name: mariadb
        state: present
    - name: install rrdtool
      yum:
        name: rrdtool
        state: present
    - name: install subversion
      yum:
        name: subversion
        state: present
    - name: install whois
      yum:
        name: whois
        state: present
    - name: install ipmitool
      yum:
        name: ipmitool
        state: present
    - name: install graphviz
      yum:
        name: graphviz
        state: present
    - name: install ImageMagick
      yum:
        name: ImageMagick
        state: present
    - name: install php-sodium  
      yum:
        name: php-sodium
        state: present
    - name: install python3
      yum:
        name: python3
        state: present
    - name: install python3-PyMySQL
      yum:
        name: python3-PyMySQL
        state: present
    - name: install wget
      yum:
        name: wget
        state: present
    - name: install httpd
      yum:
        name: httpd
        state: present
    - name: install libvirt
      yum:
        name: libvirt
        state: present
    - name: create observium directory
      file:
        path: /opt/observium
        state: directory
        mode: 0755
      become: yes
      become_method: sudo
      become_user: root
    - name: download observium
      get_url:
        url: http://www.observium.org/observium-community-latest.tar.gz
        dest: /opt/observium/observium-community-latest.tar.gz
        mode: 0755
      become: yes
      become_method: sudo
      become_user: root

    - name: extract observium
      unarchive:
        src: /opt/observium/observium-community-latest.tar.gz
        dest: /opt/observium
        remote_src: yes
      become: yes
      become_method: sudo
      become_user: root

    - name: enable mariadb
      systemd:
        name: mariadb
        enabled: yes
        state: started
      become: yes
      become_method: sudo
      become_user: root

    - name: mysql_secure_installation
      mysql_user:
        login_user: root
        login_password: ''
        name: root
        password: Etudiant_007
        priv: "*.*:ALL,GRANT"
        state: present
      become: yes
      become_method: sudo
      become_user: root

    - name: create database
      mysql_db:
        name: observium
        state: present
        login_user: root
        login_password: Etudiant_007
      become: yes
      become_method: sudo
      become_user: root

    - name: create user
      mysql_user:
        name: observium
        password: Etudiant_007
        priv: "*.*:ALL,GRANT"
        state: present
        login_user: root
        login_password: Etudiant_007
      become: yes
      become_method: sudo
      become_user: root

    - name: create observium config
      copy:
        src: /opt/observium/config.php.default
        dest: /opt/observium/config.php
        mode: 0755
      become: yes
      become_method: sudo
      become_user: root

    - name: create observium database
      shell: php /opt/observium/discovery.php -u
      become: yes
      become_method: sudo
      become_user: root

    - name: Install Fping
      package:
        name: fping
        state: present

    - name: Configure Observium
      lineinfile:
        path: /opt/observium/config.php
        regexp: '^//\s*\$config\[.fping.\]'
        line: '$config[\'fping\'] = "/sbin/fping";'
        state: present

    - name: Disable SELinux temporarily
      command: setenforce 0

    - name: Disable SELinux permanently
      replace:
        path: /etc/selinux/config
        regexp: '^SELINUX=.*'
        replace: 'SELINUX=permissive'

    - name: Create rrd directory
      file:
        path: /opt/observium/rrd
        state: directory
        owner: apache
        group: apache

    - name: Create observium.conf file for Apache
      copy:
        dest: /etc/httpd/conf.d/observium.conf
        content: |
          <VirtualHost *>
            DocumentRoot /opt/observium/html/
            ServerName observium.domain.com
            CustomLog /opt/observium/logs/access_log combined
            ErrorLog /opt/observium/logs/error_log
            <Directory "/opt/observium/html/">
              AllowOverride All
              Options FollowSymLinks MultiViews
              Require all granted
            </Directory>
          </VirtualHost>

    - name: Create logs directory for Observium
      file:
        path: /opt/observium/logs
        state: directory
        owner: apache
        group: apache

    - name: Add user to Observium
      command: php adduser.php "{{ observium_user }}" "{{ observium_password }}" "{{ observium_level }}"
      args:
        chdir: /opt/observium

    - name: create observium cron
      cron:
        name: observium
        minute: "*/6"
        job: php /opt/observium/discovery.php -h all >> /dev/null 2>&1
      become: yes
      become_method: sudo
      become_user: root

    - name: create observium cron
      cron:
        name: observium
        minute: "*/5"
        job: php /opt/observium/discovery.php -h new >> /dev/null 2>&1
      become: yes
      become_method: sudo
      become_user: root

    - name: create observium cron
      cron:
        name: observium
        minute: "*/5"
        job: php /opt/observium/poller-wrapper.py >> /dev/null 2>&1
      become: yes
      become_method: sudo
      become_user: root

    - name: create observium cron
      cron:
        name: observium
        minute: "13 5"
        job: php /opt/observium/housekeeping.php -ysel
      become: yes
      become_method: sudo
      become_user: root

    - name: create observium cron
      cron:
        name: observium
        minute: "47 4"
        job: php /opt/observium/housekeeping.php -yrptb
      become: yes
      become_method: sudo
      become_user: root

    - name: Reload crond
      systemd:
        name: crond
        state: reloaded

    - name: Enable httpd service
      systemd:
        name: httpd
        enabled: yes
        state: started

    - name: Allow HTTP traffic through firewall
      firewalld:
        service: http
        permanent: yes
        state: enabled

    - name: Reload firewall
      firewalld:
        reload: yes


